- name: Deploy UserService to k8s
  hosts: Local
  connection: local
  vars_files:
    - ../credentials.yml
  tasks:
    - name: Apply user-service service
      kubernetes.core.k8s:
        kubeconfig: ../twc-witty-cetus-config.yml
        namespace: makewish
        state: present
        src: ../services/user-service/service.yml
    - name: Apply user-service deployment
      kubernetes.core.k8s:
        kubeconfig: ../twc-witty-cetus-config.yml
        namespace: makewish
        state: present
        definition: "{{ lookup('template', '../services/user-service/deployment.yml.j2') }}"
