- name: Deploy WishService to k8s
  hosts: Local
  connection: local
  vars_files:
    - ../../vars.yml
    - ../credentials.yml
  tasks:
    - name: Apply wish-service service
      kubernetes.core.k8s:
        kubeconfig: ../twc-witty-cetus-config.yml
        namespace: makewish
        state: present
        src: ../services/wish-service/service.yml
    - name: Apply wish-service deployment
      kubernetes.core.k8s:
        kubeconfig: ../twc-witty-cetus-config.yml
        namespace: makewish
        state: present
        definition: "{{ lookup('template', '../services/wish-service/deployment.yml.j2') }}"
