networks:
  dev:

volumes:
  postgres:
  rabbitmq:
  neo4j:

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: makewish.user.service.postgres
    hostname: makewish.user.service.postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: makewish.rabbitmq
    hostname: makewish.rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - dev
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    container_name: makewish.wish.service.neo4j
    hostname: makewish.wish.service.neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j:/data
    networks:
      - dev