networks:
  dev:

volumes:
  postgres:
  rabbitmq:
  neo4j:

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: makewish.user.service.postgres
    hostname: makewish.user.service.postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: makewish.rabbitmq
    hostname: makewish.rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - dev
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    container_name: makewish.wish.service.neo4j
    hostname: makewish.wish.service.neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j:/data
    networks:
      - dev
  user-service:
    build:
      context: MakeWish.UserService
    container_name: makewish.user.service
    hostname: makewish.user.service
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtToken__SecretKey=DevelopmentSecretKey101010NotSensitiveData
      - DbConnection__ConnectionString=Server=makewish.user.service.postgres:5432;Database=postgres;Username=postgres;Password=postgres
      - RabbitConnection__ConnectionString=amqp://rabbitmq:rabbitmq@makewish.rabbitmq:5672
    networks:
      - dev
  wish-service:
    build:
      context: MakeWish.WishService
    container_name: makewish.wish.service
    hostname: makewish.wish.service
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtToken__SecretKey=DevelopmentSecretKey101010NotSensitiveData
      - DbConnection__Password=password
      - RabbitConnection__ConnectionString=amqp://rabbitmq:rabbitmq@makewish.rabbitmq:5672
    networks:
      - dev
