networks:
  dev:

volumes:
  postgres:

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - dev