apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
  namespace: makewish
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/neo4j
  persistentVolumeReclaimPolicy: Retain
