apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: makewish
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  persistentVolumeReclaimPolicy: Retain
