name: Run .NET tests

on:
  workflow_call:
    inputs:
      solution:
        description: Path to target .NET solution
        type: string
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution }}

      - name: Build solution
        run: dotnet build ${{ inputs.solution }} --no-restore
      
      - name: Run tests 
        run: dotnet test ${{ inputs.solution }}