name: UserService push

on:
  push:
    branches:
      - master
    paths:
      - MakeWish.UserService/**

jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml
    with:
      solution: MakeWish.UserService/MakeWish.UserService.sln
  build:
    uses: ./.github/workflows/build.yml
    with:
      service: users