name: users

on:
  pull_request:
    branches:
      - master
    paths:
      - MakeWish.UserService/**
      - .github/**

jobs:
  dotnet:
    uses: ./.github/workflows/dotnet.yml
    with:
      solution: MakeWish.UserService/MakeWish.UserService.sln