name: UserService pull request

on:
  pull_request:
    branches:
      - master
    paths:
      - MakeWish.UserService/**
      - .github/**

jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml
    with:
      solution: MakeWish.UserService/MakeWish.UserService.sln
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible docker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Ansible playbook
        run: |
          cd ansible/build
          make users -e version=${{ github.sha }}