name: UserService pull request

on:
  pull_request:
    branches:
      - master
    paths:
      - MakeWish.UserService/**
      - .github/**

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore MakeWish.UserService/MakeWish.UserService.sln

      - name: Build solution
        run: dotnet build MakeWish.UserService/MakeWish.UserService.sln --no-restore
      
      - name: Run tests 
        run: dotnet test MakeWish.UserService/MakeWish.UserService.sln
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible docker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Ansible playbook
        run: |
          cd ansible/build
          ansible-playbook -i inventory playbooks/user-service.yml \
            --extra-vars="version=${{ github.sha }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 185.197.75.130 >> ~/.ssh/known_hosts
      - name: Create Ansible Vault password file
        run: echo "${{ secrets.VAULT_PASSWORD_DEPLOY }}" > vault_pass.txt
      - name: Run Ansible playbook (Deploy UserService)
        run: |
          cd ansible/deploy
          ansible-playbook -i inventory playbooks/user-service.yml \
            --extra-vars="version=${{ github.sha }}" \
            --vault-password-file vault_pass.txt
      - name: Clean up
        run: rm -f ~/.ssh/id_rsa vault_pass.txt